# Generated by Django 6.0.5 on 2026-05-15 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0003_seed_document_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('form_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('tl_approved', 'TL Approved'), ('in_review', 'In Review'), ('returned', 'Returned'), ('finalized', 'Finalized')], default='draft', max_length=15)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workpapers', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workpapers', to='engagements.documenttype')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workpapers', to='engagements.engagement')),
                ('last_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_workpapers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_type__sequence_order'],
                'unique_together': {('engagement', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='WorkpaperAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ref', models.CharField(blank=True, max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('file_type', models.CharField(max_length=50)),
                ('file_size_kb', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('workpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workpapers.workpaper')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkpaperVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('form_data', models.JSONField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('autosave', 'Auto Save'), ('manual_save', 'Manual Save'), ('submission', 'Submission'), ('reviewer_edit', 'Reviewer Edit'), ('return', 'Return')], default='autosave', max_length=20)),
                ('change_summary', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workpaper_versions', to=settings.AUTH_USER_MODEL)),
                ('workpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workpapers.workpaper')),
            ],
            options={
                'ordering': ['-changed_at'],
                'unique_together': {('workpaper', 'version')},
            },
        ),
    ]
