# Generated by Django 6.0.5 on 2026-05-15 16:50

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0003_seed_document_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_document', models.CharField(max_length=20)),
                ('source_section', models.CharField(max_length=50)),
                ('trigger_question', models.TextField()),
                ('trigger_answer', models.CharField(max_length=20)),
                ('risk_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('inherent_risk_factor', models.TextField(blank=True)),
                ('risk_description', models.TextField()),
                ('assertions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('is_cotabd_specific', models.BooleanField(default=False)),
                ('is_pervasive', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('High-Pervasive', 'High-Pervasive')], max_length=20)),
                ('cotabd', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('addressed', 'Addressed'), ('dismissed', 'Dismissed')], default='active', max_length=15)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissal_reason', models.TextField(blank=True)),
                ('from_library', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_risks', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='engagements.engagement')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
