# Generated by Django 6.0.5 on 2026-05-15 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risks', '0001_initial'),
        ('workpapers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='workpaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_risks', to='workpapers.workpaper'),
        ),
    ]
