# Generated by Django 6.0.5 on 2026-05-16 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0004_engagement_lead_type_engagement_responsible_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_version', models.IntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('current_level', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('returned', 'Returned'), ('locked', 'Locked')], default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_packages', to='engagements.engagement')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('return', 'Return'), ('comment', 'Comment')], max_length=10)),
                ('returned_to_level', models.IntegerField(blank=True, null=True)),
                ('general_comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='reviews.reviewpackage')),
            ],
            options={
                'ordering': ['-acted_at'],
            },
        ),
        migrations.CreateModel(
            name='TLDocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('return', 'Return'), ('comment', 'Comment')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tl_document_reviews', to='engagements.engagement')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tl_document_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acted_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentReviewFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=20)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_comment', models.TextField(blank=True)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_flags', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_flags', to='reviews.reviewpackage')),
            ],
            options={
                'ordering': ['document_type'],
                'unique_together': {('package', 'document_type')},
            },
        ),
    ]
