# Generated by Django 6.0.5 on 2026-05-16 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0004_engagement_lead_type_engagement_responsible_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('package_path', models.CharField(blank=True, max_length=500)),
                ('total_files', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error')], default='generating', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_packages', to='engagements.engagement')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_export_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naming_pattern', models.CharField(default='[EngagementCode]_[WorkpaperRef]_[EntityName]_[Year]', max_length=200)),
                ('excel_password', models.CharField(blank=True, help_text='Password to protect exported Excel files. Leave blank for no protection.', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Settings',
                'verbose_name_plural': 'Export Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMateUploadChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('teammate_ref', models.CharField(blank=True, max_length=100)),
                ('uploaded', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('export_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='exports.exportpackage')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teammate_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_type', 'file_name'],
            },
        ),
    ]
