# Generated by Django 6.0.5 on 2026-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('POST', 'Create'), ('PUT', 'Replace'), ('PATCH', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('table_name', models.CharField(help_text='Derived from the request URL path (app/resource name).', max_length=100)),
                ('record_id', models.CharField(blank=True, help_text='Primary key extracted from the URL, if present.', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_body', models.JSONField(blank=True, help_text='Sanitised request payload (passwords redacted).', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
