# Generated by Django 6.0.5 on 2026-05-16 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='lead_type',
            field=models.CharField(blank=True, choices=[('responsible_cea', 'Responsible CEA'), ('responsible_overall_tl', 'Responsible Overall TL')], default='responsible_cea', max_length=30),
        ),
        migrations.AddField(
            model_name='entity',
            name='responsible_person',
            field=models.ForeignKey(blank=True, help_text='Current responsible CEA/TL from audit universe. Used as suggestion when creating engagements.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_entities', to=settings.AUTH_USER_MODEL),
        ),
    ]
