# Generated by Django 6.0.5 on 2026-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('locked', 'Locked'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('tl_approved', 'TL Approved'), ('in_review', 'In Review'), ('returned', 'Returned'), ('finalized', 'Finalized')], default='not_started', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('tl_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['document_type__sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('pre_engagement', 'Pre-Engagement'), ('understanding_entity', 'Understanding the Entity'), ('risk_assessment', 'Risk Assessment')], max_length=30)),
                ('sequence_order', models.PositiveSmallIntegerField(default=0)),
                ('unlock_after_code', models.CharField(blank=True, help_text='Code of the DocumentType that must be submitted before this one unlocks.', max_length=10, null=True)),
                ('workpaper_ref', models.CharField(blank=True, help_text='TeamMate+ workpaper reference name.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('audit_year', models.PositiveIntegerField()),
                ('audit_period_start', models.DateField()),
                ('audit_period_end', models.DateField()),
                ('reporting_framework', models.CharField(choices=[('ipsas', 'IPSAS'), ('ifrs', 'IFRS'), ('ifrs_sme', 'IFRS for SMEs'), ('local_gaap', 'Local GAAP'), ('other', 'Other')], default='ipsas', max_length=20)),
                ('reporting_currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='TZS', max_length=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('locked', 'Locked'), ('archived', 'Archived')], default='active', max_length=15)),
                ('overall_deadline', models.DateField(blank=True, null=True)),
                ('submitted_to_cea_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-audit_year', 'entity__name'],
            },
        ),
        migrations.CreateModel(
            name='EngagementTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_role', models.CharField(choices=[('financial_auditor', 'Financial Auditor'), ('is_auditor', 'IS Auditor'), ('team_leader', 'Team Leader'), ('cea', 'Chief External Auditor'), ('other', 'Other')], default='financial_auditor', max_length=25)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['engagement_role', 'user__full_name'],
            },
        ),
    ]
