# Generated by Django 6.0.5 on 2026-05-15 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engagements', '0001_initial'),
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentassignment',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='engagements.documenttype'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagement',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='entities.entity'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagement',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentassignment',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_assignments', to='engagements.engagement'),
        ),
        migrations.AddField(
            model_name='engagementteam',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engagementteam',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='engagements.engagement'),
        ),
        migrations.AddField(
            model_name='engagementteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='engagement',
            unique_together={('entity', 'audit_year')},
        ),
        migrations.AlterUniqueTogether(
            name='documentassignment',
            unique_together={('engagement', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='engagementteam',
            unique_together={('engagement', 'user')},
        ),
    ]
