# Generated by Django — seed DocumentType records for all 13 standard document types.

from django.db import migrations


DOCUMENT_TYPES = [
    # Pre-engagement documents
    {
        'code': 'PE1',
        'name': 'Independence and Ethics Confirmation',
        'category': 'pre_engagement',
        'sequence_order': 10,
        'unlock_after_code': None,
        'workpaper_ref': 'PE-1 Independence',
        'is_active': True,
    },
    {
        'code': 'PE2',
        'name': 'Engagement Acceptance / Continuance',
        'category': 'pre_engagement',
        'sequence_order': 20,
        'unlock_after_code': 'PE1',
        'workpaper_ref': 'PE-2 Acceptance',
        'is_active': True,
    },

    # Understanding the entity
    {
        'code': 'UE1',
        'name': 'Understanding the Entity and Its Environment',
        'category': 'understanding_entity',
        'sequence_order': 30,
        'unlock_after_code': 'PE2',
        'workpaper_ref': 'UE-1 Entity Understanding',
        'is_active': True,
    },
    {
        'code': 'UE2',
        'name': 'Understanding Internal Controls',
        'category': 'understanding_entity',
        'sequence_order': 40,
        'unlock_after_code': 'UE1',
        'workpaper_ref': 'UE-2 Internal Controls',
        'is_active': True,
    },
    {
        'code': 'UE3',
        'name': 'IT General Controls Assessment',
        'category': 'understanding_entity',
        'sequence_order': 50,
        'unlock_after_code': 'UE2',
        'workpaper_ref': 'UE-3 IT Controls',
        'is_active': True,
    },
    {
        'code': 'UE4',
        'name': 'Analytical Procedures — Planning',
        'category': 'understanding_entity',
        'sequence_order': 60,
        'unlock_after_code': 'UE1',
        'workpaper_ref': 'UE-4 Planning Analytics',
        'is_active': True,
    },
    {
        'code': 'UE5',
        'name': 'Materiality Determination',
        'category': 'understanding_entity',
        'sequence_order': 70,
        'unlock_after_code': 'UE4',
        'workpaper_ref': 'UE-5 Materiality',
        'is_active': True,
    },

    # Risk assessment documents
    {
        'code': 'RA1',
        'name': 'Risk Assessment — Inherent Risk',
        'category': 'risk_assessment',
        'sequence_order': 80,
        'unlock_after_code': 'UE5',
        'workpaper_ref': 'RA-1 Inherent Risk',
        'is_active': True,
    },
    {
        'code': 'RA2',
        'name': 'Risk Assessment — Control Risk',
        'category': 'risk_assessment',
        'sequence_order': 90,
        'unlock_after_code': 'RA1',
        'workpaper_ref': 'RA-2 Control Risk',
        'is_active': True,
    },
    {
        'code': 'RA3',
        'name': 'Risk Assessment — Detection Risk and Audit Response',
        'category': 'risk_assessment',
        'sequence_order': 100,
        'unlock_after_code': 'RA2',
        'workpaper_ref': 'RA-3 Detection Risk',
        'is_active': True,
    },
    {
        'code': 'RA4',
        'name': 'Significant Risks Summary',
        'category': 'risk_assessment',
        'sequence_order': 110,
        'unlock_after_code': 'RA3',
        'workpaper_ref': 'RA-4 Significant Risks',
        'is_active': True,
    },
    {
        'code': 'FRF',
        'name': 'Financial Reporting Framework Assessment',
        'category': 'risk_assessment',
        'sequence_order': 120,
        'unlock_after_code': 'UE3',
        'workpaper_ref': 'FRF Financial Reporting',
        'is_active': True,
    },
    {
        'code': 'AP',
        'name': 'Overall Audit Plan',
        'category': 'risk_assessment',
        'sequence_order': 130,
        'unlock_after_code': 'RA4',
        'workpaper_ref': 'AP Audit Plan',
        'is_active': True,
    },
]


def seed_document_types(apps, schema_editor):
    DocumentType = apps.get_model('engagements', 'DocumentType')
    for dt in DOCUMENT_TYPES:
        DocumentType.objects.get_or_create(code=dt['code'], defaults=dt)


def reverse_seed(apps, schema_editor):
    DocumentType = apps.get_model('engagements', 'DocumentType')
    codes = [dt['code'] for dt in DOCUMENT_TYPES]
    DocumentType.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(seed_document_types, reverse_code=reverse_seed),
    ]
